# MANE 6399 - Data Science

## Week Fifteen

## MLP Classifier

# Jupyter Example 1

## MLP Classifier

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
# read excel file into dataframe
df1 = pd.read_excel(open('wpbc.data.xlsx','rb'))
df1=df1.dropna(axis=0,how='any')       # remove rows with missing values
df1.drop('id', axis=1, inplace=True)   # drop column with patient ids
print(df1)
# create endogenous and exogenous variables
X = np.array(df1.iloc[:, 1:14])
print(X)
y = np.array(df1['recurrence'])
# split and transform data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
X_train.shape
# Transform training data
scaler=StandardScaler()
scaler.fit(X_train)
X_train_transformed=scaler.transform(X_train)
X_test_transformed=scaler.transform(X_test)
#fit model
mlp1=MLPClassifier(hidden_layer_sizes=(13,5,5))
mlp1.fit(X_train_transformed,y_train)
y_train_pred = mlp1.predict(X_train_transformed)
y_test_pred = mlp1.predict(X_test_transformed)
# produce results
print("Confusion matrix for training set")
print(confusion_matrix(y_train,y_train_pred))
print("The accuracy for the training set is %f"%mlp1.score(X_train_transformed,y_train))
print("Confusion matrix for test set")
print(confusion_matrix(y_test,y_test_pred))
print("The accuracy for the test set is %f"%mlp1.score(X_test_transformed,y_test))


    outcome  time  radius  texture  perimeter    area  smoothness  \
0         N    31   18.02    27.60     117.50  1013.0     0.09489   
1         N    61   17.99    10.38     122.80  1001.0     0.11840   
2         N   116   21.37    17.44     137.50  1373.0     0.08836   
3         N   123   11.42    20.38      77.58   386.1     0.14250   
4         R    27   20.29    14.34     135.10  1297.0     0.10030   
..      ...   ...     ...      ...        ...     ...         ...   
189       N     3   14.72    25.26      99.28   657.5     0.11740   
190       N    10   22.52    21.92     146.90  1597.0     0.07592   
191       N     8   15.44    31.18     101.00   740.4     0.09399   
192       N    12   17.17    29.19     110.00   915.3     0.08952   
193       N     6   16.70    28.13     110.30   885.4     0.08896   

     compactness  concavity  concavePoints  symmetry  fractal  tumorSize  \
0        0.10360    0.10860        0.07055    0.1865  0.06333        5.0   
1        0.27760   

C:\Users\fwn285\AppData\Local\Continuum\anaconda3\envs\env_iise\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


# Jupyter Example 2

## SVM Classifier with Linear Kernel

In [4]:
from sklearn import svm
clf1=svm.SVC(kernel='linear')
clf1.fit(X_train,y_train)
#
y_train_pred = clf1.predict(X_train_transformed)
y_test_pred = clf1.predict(X_test_transformed)
# produce results
print("Confusion matrix for training set")
print(confusion_matrix(y_train,y_train_pred))
print("The accuracy for the training set is %f"%clf1.score(X_train_transformed,y_train))
print("Confusion matrix for test set")
print(confusion_matrix(y_test,y_test_pred))
print("The accuracy for the test set is %f"%clf1.score(X_test_transformed,y_test))


Confusion matrix for training set
[[  0 106]
 [  0  39]]
The accuracy for the training set is 0.268966
Confusion matrix for test set
[[ 0 42]
 [ 0  7]]
The accuracy for the test set is 0.142857


# Jupyter Example 3

## Grid Search for Example 2

In [5]:
from sklearn.model_selection import GridSearchCV
Cs=[.001,.01,.1,1,10,100]
param_grid={'C': Cs}
grid_search=GridSearchCV(svm.SVC(kernel='linear'), param_grid, cv=5,verbose=10,n_jobs=-1)
grid_search.fit(X,y)
print(grid_search.best_params_)

Fitting 5 folds for each of 6 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    2.0s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    2.5s
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    9.1s
[Parallel(n_jobs=-1)]: Done  27 out of  30 | elapsed:  1.4min remaining:    8.9s


{'C': 0.001}


[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:  1.7min finished


In [6]:
# implement best model
clf2=svm.SVC(kernel='linear',C=0.001)
clf2.fit(X_train,y_train)
#
y_train_pred = clf2.predict(X_train_transformed)
y_test_pred = clf2.predict(X_test_transformed)
# produce results
print("Confusion matrix for training set")
print(confusion_matrix(y_train,y_train_pred))
print("The accuracy for the training set is %f"%clf2.score(X_train_transformed,y_train))
print("Confusion matrix for test set")
print(confusion_matrix(y_test,y_test_pred))
print("The accuracy for the test set is %f"%clf2.score(X_test_transformed,y_test))


Confusion matrix for training set
[[  0 106]
 [  0  39]]
The accuracy for the training set is 0.268966
Confusion matrix for test set
[[ 0 42]
 [ 0  7]]
The accuracy for the test set is 0.142857


# Jupyter Example 4

# More Sophisticated Grid Search

In [7]:
Cs=[.001,.01,.1,1,10,100]
gammas=[.0001, .001, .01,.1,1.]
param_grid={'kernel':('linear','rbf'), 'C': Cs, 'gamma': gammas}
grid_search2=GridSearchCV(svm.SVC(),param_grid,cv=5,n_jobs=-1)
grid_search2.fit(X,y)
print(grid_search2.best_params_)

{'C': 0.001, 'gamma': 0.0001, 'kernel': 'linear'}


In [8]:
# implement best model
clf3=svm.SVC(kernel='linear',C=0.001,gamma=.0001)
clf3.fit(X_train,y_train)
#
y_train_pred = clf3.predict(X_train_transformed)
y_test_pred = clf3.predict(X_test_transformed)
# produce results
print("Confusion matrix for training set")
print(confusion_matrix(y_train,y_train_pred))
print("The accuracy for the training set is %f"%clf3.score(X_train_transformed,y_train))
print("Confusion matrix for test set")
print(confusion_matrix(y_test,y_test_pred))
print("The accuracy for the test set is %f"%clf3.score(X_test_transformed,y_test))


Confusion matrix for training set
[[  0 106]
 [  0  39]]
The accuracy for the training set is 0.268966
Confusion matrix for test set
[[ 0 42]
 [ 0  7]]
The accuracy for the test set is 0.142857
